/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StatusAppImport } from './routes/status-app'
import { Route as HulyCloneImport } from './routes/huly-clone'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StatusAppRoute = StatusAppImport.update({
  id: '/status-app',
  path: '/status-app',
  getParentRoute: () => rootRoute,
} as any)

const HulyCloneRoute = HulyCloneImport.update({
  id: '/huly-clone',
  path: '/huly-clone',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/huly-clone': {
      id: '/huly-clone'
      path: '/huly-clone'
      fullPath: '/huly-clone'
      preLoaderRoute: typeof HulyCloneImport
      parentRoute: typeof rootRoute
    }
    '/status-app': {
      id: '/status-app'
      path: '/status-app'
      fullPath: '/status-app'
      preLoaderRoute: typeof StatusAppImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/huly-clone': typeof HulyCloneRoute
  '/status-app': typeof StatusAppRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/huly-clone': typeof HulyCloneRoute
  '/status-app': typeof StatusAppRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/huly-clone': typeof HulyCloneRoute
  '/status-app': typeof StatusAppRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/huly-clone' | '/status-app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/huly-clone' | '/status-app'
  id: '__root__' | '/' | '/huly-clone' | '/status-app'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HulyCloneRoute: typeof HulyCloneRoute
  StatusAppRoute: typeof StatusAppRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HulyCloneRoute: HulyCloneRoute,
  StatusAppRoute: StatusAppRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/huly-clone",
        "/status-app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/huly-clone": {
      "filePath": "huly-clone.tsx"
    },
    "/status-app": {
      "filePath": "status-app.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
